### ISSUE TITLE
Strange behaviour on yarn install - obsolete/ancient dependency warnings!?

### ISSUE THREAD

**Issue by kristianmandrup** [Polymer/pwa-starter-kit#100]
```bash
$ yarn install
yarn install v1.5.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning polymer-cli > bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
warning polymer-cli > github@7.3.2: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
warning polymer-cli > web-component-tester > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning polymer-cli > web-component-tester > sinon > formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
warning replace > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
warning replace > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning wct-browser-legacy > sinon > formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
info Unable to find a suitable version for "@webcomponents/webcomponentsjs", please choose one by typing one of the numbers below:
  1) "@webcomponents/webcomponentsjs@^2.0.0" which resolved to "2.0.0"
  2) "@webcomponents/webcomponentsjs@^1.0.7, @webcomponents/webcomponentsjs@^1.0.7" which resolved to "1.2.0"
Answer?: 
```

Load of warnings, such as use of bower

```bash
warning polymer-cli > bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

Loads of packages unmaintained or not supported. Looks like ancient dependencies!! What gives?

**Comment by pranavb** [comment]
Ran into the same issue. You get stuck in a huge, seemingly never ending, list of Yarn prompts, all asking for roughly the same thing. 

Seems fine with NPM apart from `npm audit` detecting 7 high and 2 critical vulnerabilities.

``

**Comment by notwaldorf** [comment]
This sounds like it's got a similar cause to #99 (a `pwa-starter-kit` dependency has other bad dependencies). It sounds like `yarn` handles this extra poorly, but im not sure what we can do to fix that 😕

**Comment by LarsDenBakker** [comment]
I think the issue here is that the package.json has flat: true set. This is picked up by yarn, but not by npm. Flat is no longer required due to named import resolution.

**Comment by keanulee** [comment]
Agreed - we should remove `flat: true`. We don't require flat installation for Node.js dependencies, but front end dependencies should be flat to avoid loading conflicting dependencies in the browser (e.g. multiple custom element definitions or multiple web component polyfills).

Note: we only want `webcomponentsjs@^2.0.0`, but wct-browser-legacy has a stale dependency to `webcomponentsjs@^1.0.7`. This should be updated in the tools repo.
