### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by univhack** [Polymer/pwa-starter-kit#101]
It looks like the starter kit is not working in IE 11 :(

![image](https://user-images.githubusercontent.com/4080811/39976921-757db1d4-5704-11e8-9a90-9885d52ad55c.png)

**Comment by hyperpress** [comment]
This was noted: Please see  Known Issues section of readme. LitElement has known compatibility issues with IE11.

**Comment by univhack** [comment]
Thanks for the quick reply!

**Comment by univhack** [comment]
Do you have a rough estimate of the timeline when it will get fixed? (We are planning to roll an app to prod in the next 3 months). IE11 users are not a core target but we will definitely have some of those

**Comment by hyperpress** [comment]
I haven't seen anything on this yet. Maybe a question to ask on LitElement (lit-html) repo for a faster reply.

**Comment by univhack** [comment]
Will do thanks for the advice!

**Comment by frankiefu** [comment]
This is the issue to follow in lit-element: https://github.com/Polymer/lit-element/issues/45

**Comment by notwaldorf** [comment]
Going to close this issue, since it's an upstream bug that we can't fix here. Please follow the `lit-element` thread for updates!

**Comment by univhack** [comment]
Thanks @frankiefu !
