### ISSUE TITLE
Any infinite-list / iron-list samples using lit-html?

### ISSUE THREAD

**Issue by Protoss78** [Polymer/pwa-starter-kit#119]
I'm wondering if it would be possible to include an infiinite list sample. Just tried to include it in one of my firebase related samples, but looks like there is no refernce code or anything out there yet.
Although iron-list or vaadin-grid is already available on npm, they are lacking samples. The existing vaadin-grid sample are still using PolymerElement.
Therefore I was wondering if it is even feasible or possible to integrate them in a lit-html sample?

**Comment by valdrinkoshi** [comment]
[`<virtual-scroller>`](https://github.com/valdrinkoshi/virtual-scroller) might help here. 
Some caveats: it is still at an early stage, and we're still working on the shape of the APIs.
Here's how it would look to use it with lit-html http://jsbin.com/gemuwiz/1/edit?html,output
```js
const newChild = (idx) => {
  const el = document.createElement('div');
  el.textContent = `index ${idx}`;
  return el;
};
const scrollerTemplate = (totalItems) => html`
   <virtual-scroller newChild=${newChild} totalItems=${totalItems} style="height: 100vh">
   </virtual-scroller>`;
      
render(scrollerTemplate(1000), document.body);
```
Similarly, with LitElement http://jsbin.com/heyilar/1/edit?html,output

**Comment by Protoss78** [comment]
Thanks a lot for the samples. Will keep an on the repo. :-)
