### ISSUE TITLE
Adding prpl-server as a library + express to the wiki

### ISSUE THREAD

**Issue by amitmerin** [Polymer/pwa-starter-kit#121]
In the wiki there is a section regarding "[building for prpl-server](https://github.com/Polymer/pwa-starter-kit/wiki/5.-Building-&-Deploying#prpl-server-recommended)".

I suggest we add a walkthrough on how to add server side logic to the project using express as mentioned in the `prpl-server-node` [readme](https://github.com/Polymer/prpl-server-node#as-a-library). 

### 1. Install express in the `server` folder
`cd server`
`npm i --save express`
### 3. Add server side logic to the file
```
// server/app.js or whatever you wish to call this file
const express = require('express')
prpl = require('prpl-server');
const app = express();

app.get('/api/launch', (req, res, next) => res.send('boom'));
let polyConfigFile = require("./build/polymer.json");
app.get('/*', prpl.makeHandler('server/build',polyConfigFile));


app.listen(3000, () => console.log('Express + prpl-server app listening on port 3000!'));
```
### 3. Add run script to root folder `package.json`
`cd ..`
```
{ ...
    "scripts": {
        ...
        "serve:prpl-server-express": "node ./server/app.js",
       ...
    },
...}
```
### 4. Dont forget to `build` so you have something to `serve`
`npm run build:prpl-server`

* Please note thet this runs a script that modifies `polymer.json` in the `server` folder:
```"build:prpl-server": "polymer build --auto-base-path && rm -rf server/build && mv build server/ && renamer --find node_modules --replace node_assets 'server/build/**' && replace node_modules node_assets server/build -r -s",```
The **`--auto-base-path`** flag adds `autoBasePath:true` to the `polymer.json` file.
This `autoBasePath:true` property is necessary in order to get the file paths right when serving the app from the `server` folder.  
### 5. Serve from `express` + `prpl-server`
`npm run serve:prpl-server-express`
And you should see something like this:
![package_json_ _my-app](https://user-images.githubusercontent.com/13625738/40373976-1a949f40-5db6-11e8-8bc9-0814d050e088.png)

**Comment by motss** [comment]
It only works for me when adding `autoBasePath: true` into `polymer.json`.

**Comment by amitmerin** [comment]
@motss That is added when you run `npm run build:prpl-server`

**Comment by motss** [comment]
@amitmerin Must be this line `polymer build --auto-base-path` which is what it does. Would it be more explicit by specifying it in `polymer.json`. AFAIK, `--module-resolution node` and `--npm` can be specified via flags but they are listed in `polymer.json`. `polymer build` by right should be able to pick up anything from `polymer.json`.

Just curious why they are being done separately. This causes confusion and it happens on me.

**Comment by amitmerin** [comment]
@motss I think you have a point, and it is probably relevant anyway to the how the project is currently configured.
I thing they didnt want to add an additional manual step of editing the `polymer.json`in the server folder. But I am just guessing. 
The purpose if my addition was to show how to add server side logic to the starter kit.
I will add a note regarding `autoBasePath:true`

**Comment by motss** [comment]
Awesome. Looks good to me. This will definitely help a lot of folks who encountered problems when things do not work as what they expect. 🎉

**Comment by itssumitrai** [comment]
Awesome, can we get this fixed please ? I ran into this same problem.

**Comment by keanulee** [comment]
`autoBasePath` isn't set in polymer.json (and `polymer build --auto-base-path` is used instead for the `build:prpl-server` script) so that the static build (`build:static`) works.

**Comment by keanulee** [comment]
For reference I wrote [a branch polymer-redux-hn](https://github.com/PolymerLabs/polymer-redux-hn/compare/push-proxy) which uses a custom express server to proxy HN API requests (so that I can h2 server push them with the response). Feel free to submit a PR to https://github.com/Polymer/pwa-starter-kit/blob/gh-pages/building-and-deploying.md - perhaps "`prpl-server` as a library" should be its own section between "`prpl-server` (recommended)" and "Static hosting".

**Comment by mercmobily** [comment]
Please add this to this page https://pwa-starter-kit.polymer-project.org/building-and-deploying#prpl-server-recommended

@keanulee  the link you provided https://github.com/Polymer/pwa-starter-kit/blob/gh-pages/building-and-deploying.md doesn't work.
I think this is a crucial addition to the docs... I am sure I am not alone.

**Comment by keanulee** [comment]
The source for that page has now been moved to https://github.com/Polymer/pwa-starter-kit/blob/docs/pages/building-and-deploying.md. I'll update the link in my previous comment as well.

**Comment by mercmobily** [comment]
I will be happy to make a PR since the original author doesn't seem to be around. @keanulee Would it be OK for you guys if I did just that?

**Comment by mercmobily** [comment]
@keanulee Quick favour... I am spending way too long reformatting the original text, as I don't have access to the markdown version of it. Would it be possible for you to click on "Edit", copy the code, and past it here *as Markdown* so that I can focus on the contents rather than the formatting?

**Comment by mercmobily** [comment]
@keanulee The steps in this guide are largely unnecessary; I suspect things have changed quite a bit since 2018. I will make a PR, but it will be pretty short.

**Comment by mercmobily** [comment]
I made the PR: https://github.com/Polymer/pwa-starter-kit/compare/docs...mercmobily:patch-1
I think this issue should be closed.

**Comment by ivanovivelin** [comment]
How can I have the polymer routes hit the express server. 

/api/* is never landed ... 

`
app.get('/api/my-view', (req, res) => {
    console.log('in my-view');
});


app.get('/*', prpl.makeHandler('./build', require('./build/polymer.json')));

app.listen(3000, () => console.log('Express + prpl-server app listening on port 3000!'));
`

**Comment by krumware** [comment]
What version of express are you using?
Also, what happens if you add a response to your function? Its possible (as written) it could just be hanging.
```
app.get('/api/my-view', (req, res) => {
console.log('in my-view');
res.json({"stuffkey","stuffvalue"});
});
```

**Comment by ivanovivelin** [comment]
> What version of express are you using?
> Also, what happens if you add a response to your function? Its possible (as written) it could just be hanging.
> 
> ```
> app.get('/api/my-view', (req, res) => {
> console.log('in my-view');
> res.json({"stuffkey","stuffvalue"});
> });
> ```

@krumware Express version is 4.17.1, basically nothing happens when I hit that route, no console log.

**Comment by krumware** [comment]
this snippit does console log for me and return (my above was incorrect)
```
app.get('/testtest', (req, res) => {
        console.log('in my-view');
        res.json({"stuffkey":"stuffvalue"});
    });
```

The only other thing I'm doing differently in a sample I have on hand at the moment, is that I'm calling app.listen before registering the routes. Not sure if that will make a difference for you, but its worth a try.
Mine roughly looks like this. Note the difference in app.listen, just another thing to try.
```
var app = express();
var server = http.createServer(app).listen(8080, function () {
    console.log('Server is listening for connections on port ' + 8080+ '.');
});

//app.get and app.use routes below.
app.get('/testtest', (req, res) => {
        console.log('in my-view');
        res.json({"stuffkey":"stuffvalue"});
    });
var polyconfig = require(UI_ROOT_PATH + "/polymer.json");
app.get('/*', prpl.makeHandler(UI_ROOT_PATH, polyconfig));
```

**Comment by ivanovivelin** [comment]
> this snippit does console log for me and return (my above was incorrect)
> 
> ```
> app.get('/testtest', (req, res) => {
>         console.log('in my-view');
>         res.json({"stuffkey":"stuffvalue"});
>     });
> ```
> 
> The only other thing I'm doing differently in a sample I have on hand at the moment, is that I'm calling app.listen before registering the routes. Not sure if that will make a difference for you, but its worth a try.
> Mine roughly looks like this. Note the difference in app.listen, just another thing to try.
> 
> ```
> var app = express();
> var server = http.createServer(app).listen(8080, function () {
>     console.log('Server is listening for connections on port ' + 8080+ '.');
> });
> 
> //app.get and app.use routes below.
> app.get('/testtest', (req, res) => {
>         console.log('in my-view');
>         res.json({"stuffkey":"stuffvalue"});
>     });
> var polyconfig = require(UI_ROOT_PATH + "/polymer.json");
> app.get('/*', prpl.makeHandler(UI_ROOT_PATH, polyconfig));
> ```

@krumware still the same here. This is structure of the folder: 


<img width="1459" alt="Screenshot 2019-08-05 at 23 50 28" src="https://user-images.githubusercontent.com/22252962/62497306-dcb3c300-b7db-11e9-84ab-44ec36137885.png">


Could you share some sample repo maybe ?

**Comment by ivanovivelin** [comment]
> > this snippit does console log for me and return (my above was incorrect)
> > ```
> > app.get('/testtest', (req, res) => {
> >         console.log('in my-view');
> >         res.json({"stuffkey":"stuffvalue"});
> >     });
> > ```
> > 
> > 
> > The only other thing I'm doing differently in a sample I have on hand at the moment, is that I'm calling app.listen before registering the routes. Not sure if that will make a difference for you, but its worth a try.
> > Mine roughly looks like this. Note the difference in app.listen, just another thing to try.
> > ```
> > var app = express();
> > var server = http.createServer(app).listen(8080, function () {
> >     console.log('Server is listening for connections on port ' + 8080+ '.');
> > });
> > 
> > //app.get and app.use routes below.
> > app.get('/testtest', (req, res) => {
> >         console.log('in my-view');
> >         res.json({"stuffkey":"stuffvalue"});
> >     });
> > var polyconfig = require(UI_ROOT_PATH + "/polymer.json");
> > app.get('/*', prpl.makeHandler(UI_ROOT_PATH, polyconfig));
> > ```
> 
> @krumware still the same here. This is structure of the folder:
> 
> <img alt="Screenshot 2019-08-05 at 23 50 28" width="1459" src="https://user-images.githubusercontent.com/22252962/62497306-dcb3c300-b7db-11e9-84ab-44ec36137885.png">
> 
> Could you share some sample repo maybe ?

@krumware issue was with using http://localhost:8080/testtest does not work , but http://127.0.0.1:8080/testtest does

**Comment by krumware** [comment]
oh strange! I'm not sure if I've come across that issue before. glad you figured it out!
