### ISSUE TITLE
es6 imports are not working properly.

### ISSUE THREAD

**Issue by bhargavkonkathi** [Polymer/pwa-starter-kit#122]
Trying to use redux-firestore but got errors like these.
The requested module '../node_modules/redux-firestore/es/index.js' does not provide an export named 'reduxFirestore'

**Comment by keanulee** [comment]
Despite the misleading directory, looks like [es/index.js](https://unpkg.com/redux-firestore@0.5.4/es/index.js?module) isn't actually an ES module (doesn't use `export { reduxFirestore }` syntax). For reference, it should look like [Redux](https://unpkg.com/redux@4.0.0/es/redux.js?module). Consider making an issue with redux-firestore.

**Comment by goatandsheep** [comment]
@keanulee is there a way to compile it anyway using a gulp plugin?

**Comment by keanulee** [comment]
I'm unaware of any ways to convert `module.exports` code to ES modules (so that it can be safely consumed by our tools).

**Comment by goatandsheep** [comment]
Ok. I'll wait for a webpack template then before I experiment. Cheers!

**Comment by frankiefu** [comment]
One workaround which you can give it a try... if the library provides an UMD build (which I believe `redux-firestore` does) you could try to import the UMD module from a JavaScript module and have it export to the global object.
e.g.
```js
import 'redux-firestore/dist/redux-firestore.js';

const { reduxFirestore } = self.ReduxFirestore;
```
This might not work if the library is not doing the right thing... see this [issue](https://github.com/umdjs/umd/issues/124) for more info.
