### ISSUE TITLE
Will template-responsive-drawer-layout stay in sync?

### ISSUE THREAD

**Issue by mercmobily** [Polymer/pwa-starter-kit#131]
As of today, template-responsive-drawer-layout is a couple of weeks behind master.
Can we expect this branch to be kept in sync consistently?
This is an especially important branch, since it has the same functionalities as the "original" PSK...

**Comment by Dabolus** [comment]
Yes, take a look at #126

**Comment by mercmobily** [comment]
Sorry, I had missed that. I assumed you'd do the merging without a PR for some reason.
In the longer term, we can expect development to be carried on in master, and then being merged with template-responsive-drawer-layout periodically?

I am about to start porting a new project from PSK to PWA (it's more a rewrite, I know... arghhhh) and am figuring things out.

Thanks!

**Comment by Dabolus** [comment]
#126 has been merged!

Btw I can't talk on behalf of the Polymer team, but I'm quite sure they're going to keep all the templates in sync

**Comment by notwaldorf** [comment]
Yup, we're definitely trying to keep them in sync! If they aren't, it's by accident, not a deliberate decision
