### ISSUE TITLE
Vulnerability Found on "renamer" Dev Dependency

### ISSUE THREAD

**Issue by samcarecho** [Polymer/pwa-starter-kit#132]
The NPM audit security report is warning about 2 low vulnerabilities related to the package "renamer", a PWA Starter Kit dev dependency.

Prototype Pollution
renamer > app-usage-stats > usage-stats > cli-commands >command-line-usage > table-layout > deep-extend
https://nodesecurity.io/advisories/612

Prototype Pollution
renamer > command-line-tool > command-line-usage >table-layout > deep-extend
https://nodesecurity.io/advisories/612

According to 'npm audit', the solution would be updating "renamer" to version 0.7.0

**Comment by keanulee** [comment]
Fixed by https://github.com/Polymer/pwa-starter-kit/commit/3be326207307527259c609444b16c0341b828eac
