### ISSUE TITLE
Incorrect export when `await` the same file several times

### ISSUE THREAD

**Issue by Synopticum** [Polymer/pwa-starter-kit#136]
Checked on the latest version, 0.8.0 at the moment. 

Steps to reproduce:
- Replace `switch` in `src/actions/app.js` by the following one:
```
switch(page) {
    case 'view1':
      await import('../components/my-view1.js');
      // Put code here that you want it to run every time when
      // navigate to view1 page and my-view1.js is loaded
      break;
    case 'view2':
      await import('../components/my-view1.js');
      await import('../components/my-view2.js');
      break;
    case 'view3':
      await import('../components/my-view1.js');
      await import('../components/my-view3.js');
      break;
    default:
      await import('../components/my-view404.js');
  }
```
- Run `npm run build:prpl-server` or `npm run build:static`
- Run `npm run serve:prpl-server` or `npm run serve:static`
- Open the app in browser

Expected result:
- The app is working

Current result:
- The app is broken due to `Uncaught (in promise) SyntaxError: The requested module './my-app.js' does not provide an export named 'html'`

The actual reason of this error is that `export` in the built `my-app.js` is incorrect. The expected one:
`export{appLayoutBehavior as $appLayoutBehavior,appScrollEffectsBehavior as $appScrollEffectsBehavior, [... a lot of exports ....], PageViewElement,SharedStyles,app$1 as $appDefault,store};`

The real one:
`export{UPDATE_PAGE,UPDATE_OFFLINE,UPDATE_DRAWER_STATE,OPEN_SNACKBAR,CLOSE_SNACKBAR,navigate,showSnackbar,updateOffline,updateLayout,updateDrawerState};` which is actually `/src/actions/app.js` export

**Comment by frankiefu** [comment]
This sounds like a bug in `polymer build`. Can you find the issue in the [polymer tools repo](https://github.com/Polymer/tools/issues)? Thanks!

**Comment by keanulee** [comment]
Ref #142, which is a PR that would remove `await` from the source (for a different reason).

**Comment by Synopticum** [comment]
@keanulee replacing `await`s to thenable imports didn't help. For my case I solved it by importing repeating file once, before `switch`. It's not so flexible as I wanted but works.

@frankiefu I'll try to find it or create it there.
