### ISSUE TITLE
Improve the build process

### ISSUE THREAD

**Issue by abdonrd** [Polymer/pwa-starter-kit#137]
In the `build:static` step, we don't need to create the three builds (`es5-bundled`, `es6-bundled` & `esm-bundled`), we only need the `es5-bundled` build.

---

Also, the `build:prpl-server` gulp task could directly use the `clean:prpl-server` gulp task, as the Polymer CLI, we always want to clean it. Also, the `build:prpl-server` npm script would be simpler:

```
"build:prpl-server": "gulp build:prpl-server",
```

**Comment by keanulee** [comment]
Technically you don't need all 3 builds, but we build all 3 so you can select the one you need depending on your browser support requirements (and allows us to reuse the same polymer.json). We think once users choose their desired build target (prpl-server or any one of the static builds), they will likely modify polymer.json and package.json to remove the other unused build targets.

Will make a PR for condensing the gulpfile shortly.
