### ISSUE TITLE
Dynamic expressions for import() are broken after polymer build

### ISSUE THREAD

**Issue by bhargavkonkathi** [Polymer/pwa-starter-kit#146]
Unable to use expression literals for import path. 

For example, if route path is /page/subpage, I'm trying to import subpage like this. 
await import(`../components/${page}/${subpage}.js`);
Above line of code is working fine before build. But after polymer build throwing error for imports.

After build also it should support imports dynamically. Otherwise writing imports based on path would little heavy if one have more paths and subpath routes.

Thanks.

**Comment by jsilvermist** [comment]
Unfortunately I don't think `fragments` uses globs or you could do something like `**/prefix-view-*.js`.

Worth a try I suppose, maybe open an issue for that in `tools` to assist the use of dynamic imports if it's not supported.

**Comment by keanulee** [comment]
Closing - track with issue in tools repo.
