### ISSUE TITLE
PRPL Server Question

### ISSUE THREAD

**Issue by robmontesinos** [Polymer/pwa-starter-kit#149]
HI guys, I came across the PRPL server and initially it looked like a Godsend as to what I am trying to accomplish.

I wish to have a static polymer index.html file which presents a bunch of static information to the user as well as a Node server running in the functions area that renders out a separate polymer html file with dynamic content from Firestore. How would I route these requests? I added a link in the main index.html file for the following path: '/comments' - below is the modified index.js file in functions folder.

```
const functions = require('firebase-functions');
const prpl = require('prpl-server');
const express = require('express');
const rendertron = require('rendertron-middleware');

const app = express();

app.use(rendertron.makeMiddleware({
  proxyUrl: 'https://render-tron.appspot.com/render',
  injectShadyDom: true,
}));

app.get('/comments', (request, response) => {
  response.send('<h1>Comments</h1>');
});

app.get('/*', prpl.makeHandler('./build', require('./build/polymer.json')));



exports.app = functions.https.onRequest(app);
```
Any help would be greatly appreciated.

**Comment by keanulee** [comment]
prpl-server isn't a templating engine - it just picks a build directory based on UA string and responds with the index.html in that directory. You can write your own express handlers for other routes (as you have with '/comments' above), but that works outside of prpl-server.
