### ISSUE TITLE
How to create http2-push-manifest?

### ISSUE THREAD

**Issue by bisqet** [Polymer/pwa-starter-kit#156]
Hi, sorry, I tried to use [http2-push-manifest](https://github.com/GoogleChromeLabs/http2-push-manifest) but seems like it can't work with es6 modules. For now, we have a tool which can create push manifest?

**Comment by keanulee** [comment]
For pwa-starter-kit we wrote our own [push-manifest.json](https://github.com/Polymer/pwa-starter-kit/blob/master/push-manifest.json) knowing what fragments each route (URL) will load. This format is understood by [prpl-server](https://github.com/Polymer/prpl-server-node#push-manifest). We currently don't have a generalized tool that handles this process.
