### ISSUE TITLE
Is lit-html#map the successor for dom-repeat?

### ISSUE THREAD

**Issue by TimPietrusky** [Polymer/pwa-starter-kit#170]
I was trying to find an example of having `dom-repeat` in the starter-kit, but I only could find this commit https://github.com/Polymer/pwa-starter-kit/commit/73b9105a2f641aab537f9fabf071537fa25b91a4#diff-5ae7aae99baa59f89af90d458c0230aeL14

In there `dom-repeat` was removed for `.map` in combination with nested templates. 

I guess because this starter-kit is the new standard on how to build apps, we should ditch `dom-repeat`? Or what is the recommendation here?

**Comment by notwaldorf** [comment]
To repeat elements, you can use the `repeat` directive ([example from the flash-cards app](https://github.com/notwaldorf/flash-cards/blob/master/src/components/play-page.js#L72)) like this:
```html
<p>
  ${repeat(someArray, item => html`<div>${item}</div>`)}
</p>
```

Note you'll have to import it via `import { repeat } from 'lit-html/lib/repeat.js';`
