### ISSUE TITLE
API middleware for Redux in PWA Starter Kit

### ISSUE THREAD

**Issue by jhnferraris** [Polymer/pwa-starter-kit#172]
Hello, 

I'm quite new on this tool and I just want to ask if you guys have a suggested Redux API middleware tool? Tried using [redux-api-middleware](https://www.npmjs.com/package/redux-api-middleware#a-simple-example) but I always get this error

```
Uncaught SyntaxError: The requested module '../node_modules/redux-api-middleware/lib/index.js' does not provide an export named 'apiMiddleware'
```

when doing `import {apiMiddleware} from 'redux-api-middleware'`

Thanks for the assist!

**Comment by keanulee** [comment]
lib/index.js doesn't appear to be an ES module (doesn't use `export { apiMiddleware }` syntax). For reference, it should look like [Redux](https://unpkg.com/redux@4.0.0/es/redux.js?module). Consider making an issue with redux-api-middleware.

**Comment by keanulee** [comment]
Consider using `redux-api-middleware@3.0.0-beta.1` which offers ES modules as well.
