### ISSUE TITLE
prpl-server and unsupported browsers

### ISSUE THREAD

**Issue by johnthad** [Polymer/pwa-starter-kit#183]
My company has customers where individuals are still running IE9 and IE10 (like government agencies with very old desktops). It seems from the source that prpl-server is supposed to respond to unsupported browsers with a 500 error and the plain text message, "This browser is not supported." That's fine with me. However, when I attempt to open the pwa-starter-kit with IE10 in a Windows 7 VM, prpl-server tries to load build/es5-bundled/index.html, producing a blank screen and the following console errors:

    HTML1414: Unexpected character: U+0021 EXCLAMATION MARK (!) 
    10.1.2.2:8888, line 1 character 18449
    HTML1416: Unexpected character in comment end. Expected "-->". 
    10.1.2.2:8888, line 1 character 18450
    SCRIPT5009: 'Set' is undefined 
    webcomponents-sd-ce-pf.js, line 66 character 224
    SCRIPT5009: 'Set' is undefined 
    10.1.2.2:8888, line 1 character 1442

Is the issue with browser-capabilities? Or is it that ua-parser-js assumes (or seems to assume) that IE is IE11? As I said, the plain message "This browser is not supported" works for me, but a blank screen is not useful to average user. Moreover I suspect my customers would like more information. I could do this with a redirect from Apache or nginx, which I'd rather avoid. So I'd like to make a feature request: An "unsupported" configuration in polymer.json for defining an unsupported browser message or page. Alternately maybe a command line arg to prpl-server with a default to something like "unsupported.html" for unsupported browsers.

**Comment by motss** [comment]
Don't think anything below IE11 is supported since they are already deprecated and receive no security updates from MS anymore.

**Comment by keanulee** [comment]
Our team policy is to support IE11+. This applies to PWA Starter Kit as well.
