### ISSUE TITLE
Errors running test on start kit

### ISSUE THREAD

**Issue by dawuzi** [Polymer/pwa-starter-kit#193]
So I cloned the start kit and ran `npm test` but I get the error I have attached with this issue. I ran the `npm test` again after running `npm run test:regenerate_screenshots` but the error persists
[error.txt](https://github.com/Polymer/pwa-starter-kit/files/2203533/error.txt)

**Comment by notwaldorf** [comment]
The error says:
```
org.openqa.selenium.SessionNotCreatedException: Could not create a session: You must enable the 'Allow Remote Automation' option in Safari's Develop menu to control Safari via WebDriver.
```

You need to follow these instructions to enable that: https://webkit.org/blog/6900/webdriver-support-in-safari-10/

**Comment by dawuzi** [comment]
Hi @notwaldorf  So I have taken the three steps highlighted in the _Running the Example in Safari_ section of the link you shared and re ran the tests. The error still persists. I am running MacOS High Sierra.

**Comment by dawuzi** [comment]
Ok I just stumbled on a link that shows the command that solves the problem. I ran this command `defaults write com.apple.Safari IncludeDevelopMenu YES` as suggested in this link [https://stackoverflow.com/questions/41629592/macos-sierra-how-to-enable-allow-remote-automation-using-command-line](link)  and the tests now run successfully 

Thanks a lot

**Comment by johnthad** [comment]
Note that if/when you upgrade Safari 10 to Safari 11, and the WebDriver extension remains installed, you must uninstall it for the tests to run. At least that was my experience.

**Comment by comlaterra** [comment]
Just in case: 
Make sure to have the option `Develop` -> `Allow remote automation` selected in the Safari you are trying to test on.
