### ISSUE TITLE
Add examples of using realtime updates / Firebase db in a Redux PWA

### ISSUE THREAD

**Issue by itsjustbrian** [Polymer/pwa-starter-kit#196]
Firebase (the database portion, in the context of this issue) is a good fit for PWAs built with Polymer and a lot of them have chosen it as their home, myself included. The PolymerFire elements made this interaction very straightforward in the 1.0-3.0 two-way binding realm. Now that one-way binding and Redux is the endorsed method with lit-element, it would be helpful to have some examples or a best-practices guide for using a Firebase database.

Particularly, data listeners (or any realtime updates in general) confuse me in the context of Redux.
How do actions that write data to the db work when there is a listener on that same reference?
What about when there isn't a listener? Does the behavior of the action need to change in that case?
How would attaching and detaching listeners work?

Using both Redux and Firebase can feel strange because Firebase accomplishes many of the same goals as a flux system like Redux. The local copy of your db it keeps is like the store, and listeners act a lot like subscribing to that store. For this reason some people don't recommend using them together, but more often than not you don't want all of your application state going through the network layer.

Maybe my questions/concerns can just be addressed in this issue, but since PolymerFire exists there's sort of a precedent of Polymer + Firebase working together, and I'm sure a lot of people could benefit from some official guidance on how to do it with lit-element / Redux

**Comment by fafcrumb** [comment]
@IadityaM I think your issue might have more to do with the Firebase modules not supporting ESM. The polymer-cli only supports serving and building projects with ESM. To load Firebase in the starter kit, as of right now, you need to use the old fashioned script tags. Check out this issue for more info https://github.com/firebase/firebase-js-sdk/issues/815

**Comment by fleckdalm** [comment]
Any updates on this or best practice examples?
