### ISSUE TITLE
Docs: First level list elements show no bullet

### ISSUE THREAD

**Issue by djlauk** [Polymer/pwa-starter-kit#197]
Hi

I noticed some of the docs read oddly, i.e. some sentences seem incomplete, as if they were bullets in a list (e.g. the [explanations of the folder structure](https://polymer.github.io/pwa-starter-kit/configuring-and-personalizing/#folder-structure)). Looking at the source, it turns out: They _are_ bullets, but the effective style is `list-style-type: none`.

I think I spotted a CSS rule in `main.css` which is a bit too general, and I'd be happy to provide a PR with the fix, but first I wanted to make sure, that this styling is not intentional. (Sorry if I am missing something obvious.)

**Comment by notwaldorf** [comment]
Oh you're totally right, my bad!
