### ISSUE TITLE
Switch to redux-observable

### ISSUE THREAD

**Issue by arjunyel** [Polymer/pwa-starter-kit#201]
Since one of Polymer's core missions is #UseThePlatform and Observable's are on the way to being [added to Javascript](https://github.com/tc39/proposal-observable) what above switching from redux-thunk to [redux-observable](https://redux-observable.js.org/)?

**Comment by sdyalor** [comment]
Required

**Comment by phidias51** [comment]
If you're going to do that, then fork the starter kit (probably a good idea anyway), so that we have:

- a plain HTML app with no persistence
- a Firebase app which doesn't need redux.
- a redux app
