### ISSUE TITLE
Nested Routes example

### ISSUE THREAD

**Issue by qertis** [Polymer/pwa-starter-kit#202]
For example "/user/:id"

**Comment by uwerelax** [comment]
`export const navigate = (path) => (dispatch, getState) => {

  const parts = path === '/' ? ['home'] : path.slice(1).split('/');
  const routes = {
    id: parseInt(parts.find( ( part ) => !isNaN( part ))),
    create: parts.find( ( part ) => part === 'create') ? true : false,
    update: parts.find( ( part ) => part === 'update') ? true : false,
    page: parts[ 0 ]
  }
  
  dispatch(loadPage( routes ));
};

const loadPage = ( routes ) => ( dispatch ) => {
  if ( routes.page === 'user') {
    if( routes.id && routes.update ) {
      import('../views/user/user-update.js');
    } else if( routes.id ) {
      import('../views/user/user-view.js');
    } else if( routes.create ) {
      import('../views/user/user-create.js');
    } else {
      import('../views/user/users.js');
    }
  }
};
`

**Comment by frankiefu** [comment]
Also you can take a look at the Shop app which has paths like `<page>/<category>/<item>`:
https://github.com/Polymer/shop/blob/lit-element/src/actions/app.js#L56-L60
