### ISSUE TITLE
Question: How to correctly license/copyright a project based on pwa-starter-kit?

### ISSUE THREAD

**Issue by djlauk** [Polymer/pwa-starter-kit#208]
Hi!

When I use pwa-starter-kit as the starting point for my own app, how and where do I need to reference it so that all is fine?

The [docs](https://polymer.github.io/pwa-starter-kit/) provides no hint on that, and the [sample apps](https://polymer.github.io/pwa-starter-kit/sample-apps/) are all also using the same header (i.e. Copyright by the *Polymer Project Authors*).

Specifically, I have the following two (sets of) questions:

1. Would it be enough to just use the "built with pwa-starter-kit" badge and mention/link to it on the project's README page? Or do I need to attribute to pwa-starter-kit in each source file, too?
1. Can I use any license for my own app (i.e. AGPL, MIT, ...) or would/should I need to stick to the BSD style license, too?

I am sorry, if I missed anything obvious...

Thanks,
DJ

PS: I would offer to write some additional documentation on the subject.

**Comment by keanulee** [comment]
As noted at the top of all source files and package.json, this project is licensed under BSD-3-Clause:

```
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
```

In the interest of not having duplicate sources of information, follow the given link for more details http://polymer.github.io/LICENSE.txt.

**Comment by keanulee** [comment]
A link to that canonical URL in the docs would be helpful, but again, I would like to avoid having multiple sources of the same license.

**Comment by djlauk** [comment]
So, if I put a header like this in all my source files for an app:
```
This file is part of the Foo web app.

Copyright (c) 2018 ... All rights reserved.
Foo web app is distributed under the terms of the ... license. See LICENSE.txt for details.

Foo web app is built on pwa-starter-kit, which is licensed under a BSD style license.
For details see http://polymer.github.io/LICENSE.txt
```

Would that be correct and sufficient?
