### ISSUE TITLE
Replace app-layout in template-responsive-drawer-layout with something lightweight

### ISSUE THREAD

**Issue by mercmobily** [Polymer/pwa-starter-kit#209]
Hi,

I would like to use template-responsive-drawer-layout and the new material elements. What puts me off, is that it bloats the end results with Polymer (as well as  iron-flex-layout iron-media-query iron-resizable-behavior iron-scroll-target-behavior).

Can app-layout be swapped with something lightweight without dependencies?

**Comment by frankiefu** [comment]
The plan is to replace Polymer 3 elements (e.g. header, drawer) with the next-gen/[MWC](https://github.com/material-components/material-components-web-components) elements. Unfortunately we are not there yet. That is the last remaining [TODO](https://github.com/Polymer/pwa-starter-kit#todos) in PWA starter kit. There are already some elements in the MWC repo and the team is working on getting the remaining ones done. Unfortunately I don't have a solid timeline when the next-gen successors will be available but it's very high on the priority list.

**Comment by mercmobily** [comment]
I didn't think the MWC elements had layout elements too, and I didn't think the material specs covered draws etc...

**Comment by JosefJezek** [comment]
@mercmobily https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer

**Comment by mercmobily** [comment]
Ah things I didn't know...

**Comment by frankiefu** [comment]
Closing this in favor of https://github.com/Polymer/pwa-starter-kit/issues/220
