### ISSUE TITLE
Migrate to Workbox

### ISSUE THREAD

**Issue by evayde** [Polymer/pwa-starter-kit#211]
While there is no hesitation to migrate the whole project to WB here, we could add a guide to the documentation for users who already want to. Any thoughts on this? Or are there already some plans to migrate the whole starter kit any time soon?

**Comment by jsilvermist** [comment]
See Polymer/tools#388.

**Comment by JosefJezek** [comment]
Duplicate of https://github.com/Polymer/pwa-starter-kit/issues/90
