### ISSUE TITLE
Promise rejection: Error: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by budaii79** [Polymer/pwa-starter-kit#217]
Hello! 

When I serve my app everything works fine. The problems occurs when I try to build my app. I do not understand what is happening and the log from npm is not helping me very much. 

Could someone give me some hints where to start?

![38828214_271747373636483_4378271618384789504_n](https://user-images.githubusercontent.com/15094831/43874124-a61f6cec-9b92-11e8-962e-0adf4e0b9abe.png)

**Comment by budaii79** [comment]
I tried with a clear clone of PWA starter Kit.First build was allright. After that I changed  the page name NOT THE PATH in app.js and in actions/app.js from "view1" to "home". When I rebuilded the error was back. Tried to delete all build folders, error is still there. Did the undo to initial state. Error still there. Any toughts ?

**Comment by davie-robertson** [comment]
I can answer this one as I caught me out earlier this week when a colleague used VS Code code prettyfier and it placed spaces after the import statements on the within the src/actions/app.js routing code 

```    switch (page) {
        case 'view1':
            import ('../components/my-view1.js').then((module) => {
                // Put code in here that you want to run every time when
                // navigating to view1 after my-view1.js is loaded.
            });```

**Comment by budaii79** [comment]
@davie-robertson Thank you very much my friend for the advice. It worked. When I think a spend a whole night for this! Thank you again and have a nice day!
