### ISSUE TITLE
Update to latest LitElement

### ISSUE THREAD

**Issue by frankiefu** [Polymer/pwa-starter-kit#219]
Update all the templates when the new lit-element is released.
lit-element PR: https://github.com/Polymer/lit-element/pull/132
key changes:
* new lit syntax: property parts start with ".", e.g. `.foo="${foo}"`, boolean attributes start with "?", and events start with "@"
* Polymer is no longer a dependency. We've baked in what we need making things smaller and tighter.
* The properties api has [changed](https://github.com/Polymer/lit-element/blob/refactor/README.md#a-simple-base-class-for-creating-custom-elements-rendered-with-lit-html).
* The update/render lifecycle has [changed](https://github.com/Polymer/lit-element/blob/refactor/README.md#update-lifecycle).

**Comment by keanulee** [comment]
WIP over at the [`lit-element-dev` branch](https://github.com/Polymer/pwa-starter-kit/tree/lit-element-dev). Note that changes to package/-lock.json aren't included since a working version hasn't been published yet.

**Comment by kenchris** [comment]
lit-element merged the new API into master!
