### ISSUE TITLE
Replace Polymer 3 elements with MWC elements

### ISSUE THREAD

**Issue by frankiefu** [Polymer/pwa-starter-kit#220]
Once the following MWC elements are available we should update the template to use them:
Drawer: https://github.com/material-components/material-components-web-components/issues/94
Header/toolbar: https://github.com/material-components/material-components-web-components/issues/98

**Comment by mercmobily** [comment]
Thanks for this. Much better than my issue, for sure. Following it -- I hope it gets fixed soon, so that new PWAs don't need to ship with the Polymer dependency!

**Comment by tvvignesh** [comment]
It would be amazing to see the starter kit using MWC elements. Waiting eagerly for it. Any ideas on the timeline for version 1.0 release btw? I searched the whole forum but cant find any approximate dates. 

And btw, love you all for the amazing work you guys do.

**Comment by fleckdalm** [comment]
Any news or timeline on that? We are starting a new project very soon so it would be nice to know what to expect

**Comment by mercmobily** [comment]
@frankiefu How is work coming along? Is there a branch we can test?

**Comment by frankiefu** [comment]
@mercmobily We have started implementing those elements in the mwc repo. You can follow the progress here:
mwc-drawer: https://github.com/material-components/material-components-web-components/tree/master/packages/drawer
mwc-top-app-bar: https://github.com/material-components/material-components-web-components/tree/master/packages/top-app-bar

There are a few issues still need to be resolved before we can release them, and after that we will update pwa-starter-kit to use them.

**Comment by Yuen92** [comment]
@frankiefu : 
Does it make sens to also think a way to use mdc-component directly ?
https://github.com/material-components/material-components-web

To use it I think we have to add Sass and the Gulp task associated for the build.
But I don't see the good way to add the usage of the scss/css during local development. I guess the good way is to create CSSstyleSheet from css like @justinfagnani proposed here : https://github.com/Microsoft/monaco-editor/issues/886

Any thought?

**Note :**
It could be a good way to use directly mdc-component even if the target is to create MDCWebComponent 

Thanks

**Comment by abdonrd** [comment]
@frankiefu both relased!
