### ISSUE TITLE
Error serve:static es5-bundled

### ISSUE THREAD

**Issue by janioxavier** [Polymer/pwa-starter-kit#224]
I got this error in chrome dev tools console

Uncaught SyntaxError: Cannot use 'import.meta' outside a module

when run this command

yarn build:static

yarn serve:static

console output result:

applications: http://127.0.0.1:5000
reusable components: http://127.0.0.1:5000/components/es5-bundled/

To bypass, change line package-json "serve:static": "polymer serve --port 5000 build/es6-bundled" and run the command above again

console output result:

applications: http://127.0.0.1:5000
reusable components: http://127.0.0.1:5000/components/es6-bundled/

**Comment by keanulee** [comment]
I tried `npm run build:static` with the master branch and only `build/esm-bundled` (not `es5-bundled`) contained code with `import.meta`. If you installed other components that use `import.meta`, you may need to add `"transformModulesToAmd": true` to the `"js"` config in polymer.json (see https://www.polymer-project.org/3.0/toolbox/build-for-production#amd).

If this works, I suppose there's no harm to add this to our `es5-/es6-bundled` config on master.

**Comment by frankiefu** [comment]
@janioxavier Please see this issue in polymer tools: https://github.com/Polymer/tools/issues/600

**Comment by HeratPatel** [comment]
```
{
      "name": "es5-bundled",
      "js": {
        "compile": "es5",
        "minify": true,
        "transformModulesToAmd": true
      },
      "css": {
        "minify": true
      },
      "html": {
        "minify": true
      },
      "bundle": true,
      "addServiceWorker": true
    }
```

@keanulee this is my configurations for es5 build and gives me the save error.
I also added **transformModulesToAmd** to **true**
but when I change **minify** to **false** it works 
but it is not a good idea and also it gives poor performance in light-house report

can you pls help me with this

**Comment by keanulee** [comment]
Couldn't reproduce with current `master` branch:

```
npm install
npm run build:static
npm run serve:static
# open http://localhost:5000 in Chrome, page loads without errors.
```

File a new issue with more detailed repro steps if necessary.

**Comment by HeratPatel** [comment]
I did took a pull from master, still not working
here is my github repo. Can you look into it ?
For what is wrong ?

https://github.com/HeratPatel/hnpwa
