### ISSUE TITLE
Google Page Speed Insights on demo apps

### ISSUE THREAD

**Issue by casertap** [Polymer/pwa-starter-kit#227]
Hi, 
I ran page speed insight on the PWA demo apps.
The results are kind of good for desktop and kind of average/low for mobile.
The statement: `Eliminate render-blocking JavaScript and CSS in above-the-fold content` is coming often and `Prioritize visible content` as well.
Do you think it is possible to solve those issue to get a better score on page speed insight?

Another question:
None of the apps implement SSR (server-side rendering) while the PWA checklist state that the content of the website should be seen by Google (you can test using Fetch as Google tool).
I am not sure that the page speed insight tool will give me the same results as the Fetch as Google tool and because you need to own the domain name to use the Fetch as Google tool, my question is: 
Does Google is seeing the content of those pages (e.g. https://books-pwakit.appspot.com/explore?q=test )?

Thanks

**Comment by frankiefu** [comment]
I also recommend Lighthouse for testing PWA which takes a much more practical approach and puts user experience front and center. Try Google search [PageSpeed vs Lighthouse](https://www.google.com/search?q=PageSpeed+vs+Lighthouse&rlz=1C5CHFA_enUS760US760&oq=PageSpeed+vs+Lighthouse&aqs=chrome..69i57j69i60.509j0j1&sourceid=chrome&ie=UTF-8) and you can find more info.

Regarding Rendering on Google Search, @hyperpress is correct that [Googlebot is based on Chrome 41](https://developers.google.com/search/docs/guides/rendering). In `pwa-starter-kit` we recommend [prpl-server](https://polymer.github.io/pwa-starter-kit/building-and-deploying/#prpl-server-recommended) for serving your app content. This allows delivering the optimal response for each browser, including `es5-bundled` build to Googlebot. This way Googlebot can crawl your app and you don't have to worry about your app is written in ES modules/ES6/2015 code. If you don't want to use `prpl-server` then just serve `es5-bundled` build to all browsers. For example, [Books demo app](https://books-pwakit.appspot.com/) is deployed on prpl-server and you can see [site:books-pwakit.appspot.com](https://www.google.com/search?q=site%3Abooks-pwakit.appspot.com&rlz=1C5CHFA_enUS760US760&oq=site%3Abooks-pwakit.appspot.com&aqs=chrome..69i57j69i58j69i59.460j0j9&sourceid=chrome&ie=UTF-8) all the pages/views are indexed.

**Comment by hyperpress** [comment]
I should've noted that the Chrom41 issue is certainly not the fault of this Polymer, et al, and their may be sensible reasons why Googlebot remains on 41 (browser coverage?), but it's a conundrum I hope passes soon. We've not tried the most recent version of prpl, which may work fine. Would be interesting to test across demos.

**Comment by hyperpress** [comment]
I think it's safe to close this as Googlebot is based on Evergreen browsers, and our testing confirms GB can fully render the latest PWA Starter Kit.
