### ISSUE TITLE
Why was eslintrc.json removed? And what should I use for linting?

### ISSUE THREAD

**Issue by mercmobily** [Polymer/pwa-starter-kit#241]
Hi,

#69 happened in may. So, eslintrc.json was removed.
Using atom with the default packages `linter`, `linter-js-standard` and `linter-ui-default` still gives lint warnings.

What should I lint the PWA with, while using Atom?

Merc.

**Comment by keanulee** [comment]
We haven't established linting rules yet and don't intend to currently.

**Comment by mercmobily** [comment]
OK thanks for letting me know.

**Comment by miladkdz** [comment]
Any updates on this?
