### ISSUE TITLE
Lint warning using polymer-ide -- plus, unable to trigger any warnings

### ISSUE THREAD

**Issue by mercmobily** [Polymer/pwa-starter-kit#242]
Hi,

Using linter 2.2.0 and polymer-ide 0.4.0, I get a warning 

![image](https://user-images.githubusercontent.com/2128734/46567982-61417500-c970-11e8-8792-8561ad3fb448.png)

Also, it doesn't matter how much I try to stuff up spacing, enters, and all sorts of anti-lint tricks... I never get any warnings.

Isn't polymer-ide supposed to be the way we lint polymer projects?

**Comment by keanulee** [comment]
We haven't worked on polymer-ide (https://github.com/Polymer/atom-plugin) for a while, and I believe most of the team is using VS Code nowadays so it hasn't received much attention. Either way, this would be an issue for that repo.
