### ISSUE TITLE
Add more dependencies to the push-manifest.json

### ISSUE THREAD

**Issue by abdonrd** [Polymer/pwa-starter-kit#243]
We should add more dependencies to the `push-manifest.json`? Like:

* The `page-view-element.js` in all the views.
* The `counter-element.js` in the `view2`.
* The `shop-cart.js`, `shop-item.js` and `shop-products.js` in the `view3`.
* Etc

**Comment by keanulee** [comment]
These files would be bundled in the shell/fragments with the provided polymer.json config and don't exist in the build output.

**Comment by abdonrd** [comment]
Oh! Totally right, thanks @keanulee!
