### ISSUE TITLE
Wrong source maps in 'template-typescript' version

### ISSUE THREAD

**Issue by jdin** [Polymer/pwa-starter-kit#250]
The lines do not match in typescript files and that makes it impossible to debug.
Would you consider to fix it?

**Comment by abdonrd** [comment]
I have the same issue!

**Comment by keanulee** [comment]
The source maps are generated by tsc, so not sure what we can do...

**Comment by jdin** [comment]
would it be an option to combine ts with webpack or parcel?

**Comment by keanulee** [comment]
Thinking in the meanwhile we'll just disable sourcemaps.

**Comment by jdin** [comment]
I have found today 2 hours to make a small [example](https://github.com/jdin/lit-element-ts-webpack) of LitElement with TypeScript and Webpack based on `experimental branch` you have provided. Although it does not make a PWA build yet.

**Comment by keanulee** [comment]
Glad to see the webpack configuration sort of worked.

Closing since source maps are no longer generated used in `template-typescript`.

**Comment by abdonrd** [comment]
Link to tools issue: https://github.com/Polymer/tools/issues/389
