### ISSUE TITLE
Build error: '../../my-app.js' does not provide an export named 'html'

### ISSUE THREAD

**Issue by kr05** [Polymer/pwa-starter-kit#264]
I am working on a project based of the starter kit. I've had no problems until yesterday, when my build started failing. Locally, the project works fine. But after running the build:prpl-server command and serving it using serve:prpl-server, none of the views in the main-content section load. What the contents of this main-section have in common is that they are all dynamically imported. I checked my sources folder and I can confirm that the file was loaded successfully. The line that seems to be causing problems is the following:

![image](https://user-images.githubusercontent.com/11833744/47957210-e79ca700-df6e-11e8-9124-5856fc6c5485.png)

This line is the same in all of the dynamically imported views. It is what is generated by the build process. The console shows the following error when I load the page:

![image](https://user-images.githubusercontent.com/11833744/47957215-fb480d80-df6e-11e8-8c89-8b40ee3617c6.png)

The function at the very top (_loadPage) is the same function provided by the starter kit, but expanded to suit the rest of my views:

![image](https://user-images.githubusercontent.com/11833744/47957226-2c284280-df6f-11e8-8eeb-778f3f239c63.png)

What seems very odd is that all of the components that are imported statically load just fine, such as a custom footer, app-header, app-toolbar, and some other components. It's only the dynamically imported components that aren't loading. I've tried:

- creating a new project and copying over the code (it's worked before for some reason, prob due to the clean npm install)
- the import path to a constant variable before passing it as an argument to import (complete failure, polymer-cli complained about being unable to analyze the imports)
- played around with the path (./views vs ../src/views)

but nothing has worked. Any idea what the problem might be?  Thanks for the help.

**Comment by kr05** [comment]
Closing this, as I found the real reason my build was breaking: multiple dynamic imports of the same component. These errors have a very sneaky way of creeping up on you. Moral of the story: don't dynamically import a file twice.

**Comment by keanulee** [comment]
Duplicate #190. This is fixed in `master` branch of tools but waiting on a release.
