### ISSUE TITLE
How the users are notified when new version is available ?

### ISSUE THREAD

**Issue by RoXuS** [Polymer/pwa-starter-kit#273]
Hi.

Thx for this great starter kit !

The service worker are used in this project so how the users are notified when new version is available ?

**Comment by frankiefu** [comment]
We needed to do something similar in Polymer Library docs site. You can checkout the code here: https://github.com/Polymer/polymer-library-docs/blob/master/app/js/app.js#L89

If you want to learn more about service worker lifecycle: https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle

**Comment by RoXuS** [comment]
Great! Thx for your response!
