### ISSUE TITLE
[Redux DevTools] Uncaught Error: You may not call store.getState() while the reducer is executing.

### ISSUE THREAD

**Issue by Dabolus** [Polymer/pwa-starter-kit#275]
Currently, the Starter Kit is not working at all because of an "Uncaught Error":

![image](https://user-images.githubusercontent.com/28671340/49146109-bf039500-f301-11e8-95c0-ae869b393352.png)

This issue is **not** related to the Starter Kit itself, but it is caused by the latest version of Redux DevTools Extension. I'm creating this issue just to keep track of this so that folks that are going to try the Starter Kit now know why this is happening.

While the issue gets fixed on Redux DevTools extension, these are the things you can do to make it work correctly again:

1. Temporarily disable or uninstall Redux DevTools Extension
2. Manually downgrade Redux DevTools Extension to version 2.15.5 (which isn't affected by this issue) by following these steps:
   * Download Redux DevTools Extension version 2.15.5 from [here](https://github.com/zalmoxisus/redux-devtools-extension/releases/download/2.15.5/extension.zip)
   * Extract it to some folder
   * Open chrome://extensions
   * Turn on developer mode from top left
   * Click on Load Unpacked and select the folder containing the extracted extension
3. If testing the Starter Kit locally, temporarily disable (or completely remove) Redux DevTools Extension from `src/store.js:24`:
   ```diff
   - const devCompose = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
   + const devCompose = /* window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || */ compose;
   ```

Related issue: https://github.com/zalmoxisus/redux-devtools-extension/issues/588

**Comment by mskasal** [comment]
This error occurred after updating Chrome version to `70.0.3538.110`.

Removing [this line](https://github.com/Polymer/pwa-starter-kit/blob/master/src/actions/shop.js#L59) seems to fixed the problem.

**Comment by Dabolus** [comment]
Closing this as Redux DevTools Extension 2.16.3 has been released on the store and the issue has been fixed (how fast!)

**Comment by frankiefu** [comment]
@Dabolus Thanks for the quick report and the detailed workaround. And then followed up with the fix on their end. We really appreciate it.
