### ISSUE TITLE
Unable to import external styles into webcomponents.

### ISSUE THREAD

**Issue by bhargavkonkathi** [Polymer/pwa-starter-kit#276]
Hi, 

I'm are trying to use [https://quilljs.com/] (https://quilljs.com/) into lit-element. But Styles are not applied.
Any help would be appreciated.

Thank you.
Bhargav

**Comment by pinoyyid** [comment]
@bhargavkonkathi   I'm also looking to integrate QuillJS. Does it work?

**Comment by kr05** [comment]
I wasn't able to unfortunately...

**Comment by bhargavkonkathi** [comment]
Yeah it worked for me.

**Comment by bhargavkonkathi** [comment]
Install quill using npm. Here is the gist file of quill editor with lit-element working version.
https://gist.github.com/bhargavkonkathi/e393e79b43c09bc69c198cb01279d95a
