### ISSUE TITLE
How to show numeric key-board on iOS together with npm module for currency format?

### ISSUE THREAD

**Issue by Ross1307** [Polymer/pwa-starter-kit#279]
I'm building a PWA and want to show numeric key-board to users instead of text keyboard. But I also use currency masking to make sure the number is shown in right euro format.

Anybody has a solution on this? I already checked the following and many links on Stackoverflow and other groups. Maybe somebody here has a tip.

**Comment by frankiefu** [comment]
Closing as a bit out of scope for `pwa-starter-kit` project.
