### ISSUE TITLE
Visual polish on the docs site

### ISSUE THREAD

**Issue by frankiefu** [Polymer/pwa-starter-kit#283]
Just do a pass on the whole site and see if there are any visual details you wanna tweak. Particular on the [landing page](https://pwa-starter-kit.polymer-project.org/).

The docs is in the `docs` branch, e.g.
```
git clone -b docs https://github.com/Polymer/pwa-starter-kit
```
Then follow the [README](https://github.com/Polymer/pwa-starter-kit/tree/docs) to run it locally.

**Comment by keanulee** [comment]
Done
