### ISSUE TITLE
[feature request] Advanced routing support or facilitate 3rd party routing solution

### ISSUE THREAD

**Issue by syu93** [Polymer/pwa-starter-kit#286]
As the PWA Starter Kit seems to head near to production ready, I wanted to discuss this point about an advanced routing solution inside Polymer (WebComponents) ecosystem.
It might be great to add an optional (as other template flavours) advanced routing solution that provide for me the two key missing features from the previous Polymer project instalment.
* A more simple way to declare nested routes with params, as we now declare all of our routes in a single place.
* A proper way to define navigation guards.

The key point here is to make those features opt-in, as we don't want to bloat pages with unecessary code. This could be another PWA helper or an existing 3rd party routing library.

The Shop app example is maybe the right way of doing it, but we might at least have standard approach
https://github.com/Polymer/shop/blob/lit-element/src/actions/app.js#L56-L60

**Comment by ZempTime** [comment]
At my org, we moved off of the "default" pwa-starter-kit based routing to use https://github.com/vaadin/vaadin-router

Now, it's not a true usage in the sense that we don't use the vaadin-provided lifecycle methods. We actually listen on the window and react to route changes/handle everything inside redux. This has dramatically cleaned up our application, streamlined all our authentication/authorization logic, and most of all: people feel comfortable adding new routes, or figuring out which ones go where.

However, it doesn't work with query params yet, and there are bugs with nested routes (which hopefully we can get to at some point!)

So it's not _perfect_... but it's _way better_ than what we were doing. I feel comfortable suggesting this as an option to look into.
