### ISSUE TITLE
Use parcel bundler: Class constructor  cannot be invoked without 'new'

### ISSUE THREAD

**Issue by camstuart** [Polymer/pwa-starter-kit#309]
This Demo app does not live reload, and I have found examples of browser sync setup.

But https://parceljs.org is lightning fast. Has anyone succeeded in using parcel?

My setup is:

`package.json`

```json
"devDependencies": {
    "parcel-bundler": "^1.11.0"
  },
"scripts": {
    "start": "parcel index.html",
  }
```

Start up is fine, no errors or warnings. 

Chrome dev tools errors:

```
Uncaught TypeError: Class constructor  cannot be invoked without 'new'
    at new MyApp (my-app.js:235)
    at Object.parcelRequire.src/components/my-app.js.@polymer/lit-element (my-app.js:275)
    at newRequire (my-app.115f99ed.js:49)
    at my-app.115f99ed.js:81
    at my-app.115f99ed.js:107
```

At that file & line we have nothing out of the ordinary:

```javascript
window.customElements.define('my-app', MyApp);
```

**Comment by keanulee** [comment]
It's an issue with some less popular browsers (pretty sure IE but haven't verified). If you set [`"browserslist": ["> 5%"]` in package.json](https://parceljs.org/javascript.html#default-babel-transforms) It seems to work with parcel.

**Comment by keanulee** [comment]
In addition to my previous comment, `webcomponents-loader.js` assumes that polyfill bundles are located in `./bundles/*.js` relative to `webcomponents-loader.js`. Parcel breaks this assumption, so consider just loading the bundle directly. You'll also need `custom-elements-es5-adapter.js` as well.

In index.html, replace:

```html
<script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
```

with:

```html
<script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js"></script>
<script src="node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"></script>
```

**Comment by camstuart** [comment]
Unfortunately no luck. I installed the babel plugin, and created a `.babelrc`:

```json
{
  "presets": [
    "es2017"
  ],
  "plugins": [
    "@babel/plugin-transform-classes"
  ]
}
```

But the same error persists

**Comment by keanulee** [comment]
Ah, the real issue is that parcel [doesn't babel transform code in node_modules](https://parceljs.org/transforms.html#third-party-modules) which you can see in the below screenshot (still using `class`). I've read that section and don't know if I can get that working without having to modify packages on NPM. I'd suggest using the [webpack branch](https://github.com/Polymer/pwa-starter-kit/tree/webpack) for live reload.

![image](https://user-images.githubusercontent.com/1319720/51270529-05788600-197a-11e9-9087-8bee4f4492d4.png)

**Comment by camstuart** [comment]
Ahh I see.

My project is in flight, are there any instructions on applying a web pack set up to an existing project?

Is it as easy as bringing in the webpack npm's scripts and config files?

**Comment by keanulee** [comment]
No written instuctions, but you can take a look [at the diff](https://github.com/Polymer/pwa-starter-kit/compare/webpack) (there's lots of commits, but if you scroll down to files changed, it's really only the npm scripts, the config file, and minimal source changes).

**Comment by adjenks** [comment]
I can also resolve this issue by using a browserslist of `["last 1 chrome versions"]`, which was recommended here: https://github.com/parcel-bundler/parcel/issues/839

I think that is a similar or the same problem.

**Comment by isanchezd1988** [comment]
> I can also resolve this issue by using a browserslist of `["last 1 chrome versions"]`, which was recommended here: [parcel-bundler/parcel#839](https://github.com/parcel-bundler/parcel/issues/839)
> 
> I think that is a similar or the same problem.

+1 for the fix if you work with the latest browsers

However, in mi case, i want to the bundle work in ie (11 at least) and this solution no working for me :(

**Comment by zelenkoff** [comment]
Is there some updates? Adding ["last 1 chrome versions"] fixed the problem, but it's not appreciate solution...

**Comment by Makio64** [comment]
Got the same problem when i try to bundle with Webpack /babel latest... 

Also need to support edge / ie and currently with this solution it doesnt work

**Comment by Mouvedia** [comment]
.
