### ISSUE TITLE
[Improvement] Don't dispatch redux action during watcher installation

### ISSUE THREAD

**Issue by Yuen92** [Polymer/pwa-starter-kit#312]
During the load of the application ([my-app.js](https://github.com/Polymer/pwa-starter-kit/blob/master/src/components/my-app.js)) in the firstUpdated() we install some watcher in order to call redux action when : 
- route change
- network change (offline/online)
- viewport change

When we register them we dispatch the action uselessly.

Do you have a way to don't dispatch the action during the watcher installation?
Or does the enhancement should be at utility level? I mean move the issue/request directly in [pwa-helpers](https://github.com/Polymer/pwa-helpers) ?

**Expected Result :** 
The 3 actions UPDATE_PAGE, UPDATE_DRAWER_STATE, UPDATE_OFFLINE will not be performed during the application loading (only the first one isn't due to the watcher installation)
![image](https://user-images.githubusercontent.com/12259349/50939489-6a654500-147d-11e9-8196-3fe94a00fa7a.png)

**Comment by keanulee** [comment]
The initial route/network/viewport state needs to be set somehow, and I'd be interested to see alternative approaches to this (my experience with Redux before this project is limited).

**Comment by Yuen92** [comment]
Sorry my bad for the initial route. As you said we need the initial UPDATE_PAGE to define the route from the window.document.location.pathname : 
![image](https://user-images.githubusercontent.com/12259349/50996315-d9947500-1521-11e9-9ff5-9d9361ca20b6.png)

But for the drawer state we can avoid the initial UPDATE_DRAWER_STATE since we already set the state in the [src/reducers/app.js](https://github.com/Polymer/pwa-starter-kit/blob/master/src/reducers/app.js) with the constant INITIAL_STATE.
`const INITIAL_STATE = {
  page: '',
  offline: false,
  drawerOpened: false,
  snackbarOpened: false,
};`
So that's why the state doesn't change during the 3 UPDATE_DRAWER_STATE action : 
![image](https://user-images.githubusercontent.com/12259349/50996682-d948a980-1522-11e9-8eed-663d1b3603d8.png)

Same for UPDATE_OFFLINE.

If we are able to call only action needed during the initial loading then we are able to reuse the State from Redux for an anylitics purpose using Google Tag Manager/Google Analytics.
Then it will be easier to explain to business people all events.
We will have something like : 
UPDATE_PAGE => pageview
UPDATE_DRAWER_STATE => events

If we still have some unecessary UPDATE_DRAWER_STATE so we have to manage them [inside actions/app.js](https://github.com/Polymer/pwa-starter-kit/blob/master/src/actions/app.js).

**Note :** 
This improvement is really minor but it seems cleaner if we can avoid these store.dispatch.
In term of javascript execution optimisation we are talking less than 1ms on mobile (CPU 4xslowdown) :
![image](https://user-images.githubusercontent.com/12259349/50999364-47449f00-152a-11e9-8b10-1d97dbbdd7b3.png)
![image](https://user-images.githubusercontent.com/12259349/50999439-722ef300-152a-11e9-8809-82e09b9ff1cd.png)

The way it's mesured :
![image](https://user-images.githubusercontent.com/12259349/50999041-8e7e6000-1529-11e9-8bb2-bb2017e8e03f.png)
