### ISSUE TITLE
custom template

### ISSUE THREAD

**Issue by kristianmandrup** [Polymer/pwa-starter-kit#313]
Is it possible to create and reference a custom template in the CLI? 

I would like a TypeScript template without Redux (minimal) and one with my own preferred state management solution, such as Mesosis: http://meiosis.js.org/

Oh, I see there is no CLI. Simply clone whatever skeleton app/boilerplate to get going. Would be nice with a CLI as well. Perhaps even maintain a repo (or list) of proven templates. 
Cheers.

**Comment by keanulee** [comment]
We don't have an automated way to generate all the combinations of templates, but if TS + no Redux is what you want I would start with the TypeScript template and remove the Redux parts manually by following [the diff](https://github.com/Polymer/pwa-starter-kit/compare/template-no-redux).

**Comment by kristianmandrup** [comment]
Thanks. I will try that :)
