### ISSUE TITLE
[typescript branch] Cannot find name 'ClassElement' after update lit-element

### ISSUE THREAD

**Issue by abdonrd** [Polymer/pwa-starter-kit#316]
After update to lit-element v0.7.0:

<img width="1552" alt="screenshot 2019-01-11 at 00 54 46" src="https://user-images.githubusercontent.com/1007051/51004562-83ccc680-153b-11e9-818f-12dbf2809d72.png">

**Comment by abdonrd** [comment]
Fixed by https://github.com/Polymer/lit-element/pull/431

**Comment by keanulee** [comment]
Waiting on rc.2 release, then I'll update package/-lock.json on `master` and `template-typescript` branches.

**Comment by azakus** [comment]
2.0.0-rc.2 and 0.7.1 fix this issue
