### ISSUE TITLE
[lighthouse improvement] Serve static assets with an efficient cache policy

### ISSUE THREAD

**Issue by abdonrd** [Polymer/pwa-starter-kit#317]
Serve static assets with an efficient cache policy.
A long cache lifetime can speed up repeat visits to your page. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/cache-policy).

<img width="880" alt="screenshot 2019-01-11 at 13 13 42" src="https://user-images.githubusercontent.com/1007051/51033167-be1d7e80-15a2-11e9-99c5-385b41a93e5e.png">

**Comment by keanulee** [comment]
As @frankiefu mentioned in the referenced PR, a long cache policy could result in users getting a mix of old/new assets on browsers without SW pre-caching. Since the SW serves as a caching layer on supported browsers, this shouldn't be a real world issue.
