### ISSUE TITLE
How to configure a polymer 3 PWA starter app

### ISSUE THREAD

**Issue by camstuart** [Polymer/pwa-starter-kit#318]
I am assuming that future versions of this starter will include an example of a configuration file. such as a json file that is selected dynamically based on `NODE_ENV`

A good example of a data that should be stored in a configuration file would be the base path of an API endpoint, such as the one used in this example:

https://github.com/PolymerLabs/books/blob/master/src/actions/books.js#L23

I am currently considering loading a json file in the main redux store, but it would be great to understand what direction this starter kit will take, so the solution I use is somewhat consistent with future revisions of this project

**Comment by camstuart** [comment]
For the moment, I have done the following:

```javascript
npm install config
mkdir config
touch config/default.json config/index.js
```

In `config/default.json`

```json
{
  "myApp": {
    "apiBaseURI": "http://localhost:9000"
  }
}
```

In `config/index.js`

```javascript
import config from 'config'
const myAppConfig = config.get('myApp')
export default myAppConfig
```

And then in my various javascript files that need access to this configuration:

```javascript
import myAppConfig from '../config'
...
fetch(`${myAppConfig.apiBaseURI}/my-endpoint`)
```

This seems like an idiomatic solution for javascript applications. But as I said, I would like to stay consistent with this starter-kit. Unless of course you adopt this approach :)

**Comment by keanulee** [comment]
Also see #307 

No immediate plans to add configuration options ourselves, so feel free to use whatever works for your case.
