### ISSUE TITLE
Please implement built-in method(s) for any Polymer element 

### ISSUE THREAD

**Issue by Anid4u2c** [Polymer/pwa-starter-kit#335]
In file [pwa-starter-kit/src/components/my-app.js](https://github.com/Polymer/pwa-starter-kit/blob/master/src/components/my-app.js), the [app-drawer](https://github.com/Polymer/pwa-starter-kit/blob/master/src/components/my-app.js#L212) component uses one of the documented [properties](https://www.webcomponents.org/element/@polymer/app-layout/elements/app-drawer#properties), "[opened](https://www.webcomponents.org/element/@polymer/app-layout/elements/app-drawer#property-opened)", and one of the documented [events](https://www.webcomponents.org/element/@polymer/app-layout/elements/app-drawer#events), "[opened-changed](https://www.webcomponents.org/element/@polymer/app-layout/elements/app-drawer#event-opened-changed)" like this:
`      
      <app-drawer .opened="${this._drawerOpened}" @opened-changed="${this._drawerOpenedChanged}">`

I'd like to see an implementation of one of the documented [methods](https://www.webcomponents.org/element/@polymer/app-layout/elements/app-drawer#methods), like [toggle](https://www.webcomponents.org/element/@polymer/app-layout/elements/app-drawer#method-toggle)... I understand the Polymer team has done quite a bunch of work regarding moving away from Bower to NPM, and streamlining documentation ([github.com](https://github.com/PolymerElements/app-layout), [npmjs.com](https://www.npmjs.com/package/@polymer/app-layout), [webcomponents.org](https://www.webcomponents.org/element/@polymer/app-layout/elements/app-drawer), yet webcomponents.org remains the only source for sub-elements (like app-drawer).

I did successfully implement a test button that when fired determines the state of _drawerOpened and fires updateDrawerState:
`  _testButtonClicked(e) {
	  const newState = !this._drawerOpened;
	  store.dispatch(updateDrawerState(newState));
  }`

The example above get's the job done, yet I'm still wondering how to access the documented [methods](https://www.webcomponents.org/element/@polymer/app-layout/elements/app-drawer#methods).  I checked out the Polymer 3 docs, and I really hope that we don't have to [add event listener manually](https://polymer-library.polymer-project.org/3.0/docs/first-element/step-4), like with custom elements...?

I hope it's clear that I did some digging, and I really hope it's something simple, like syntax or something.

**Comment by keanulee** [comment]
In the "functional UI" pattern (i.e. `UI = f(state)` ) we're striving for in LitElement/pwa-starter-kit, we try to avoid having to get references and call methods on rendered DOM elements (similar to [React's opinion on refs](https://reactjs.org/docs/refs-and-the-dom.html)). However, in cases where you do need DOM references, you can do so in the [`updated` method](https://lit-element.polymer-project.org/guide/lifecycle#updated). For example, we had to do this in Shop:

https://github.com/Polymer/shop/blob/085f972bcdde326226fd5f35c181a5d80d6c4a72/src/components/shop-app.js#L318-L319

**Comment by Anid4u2c** [comment]
Thanks again @keanulee!  I guess it's clear that I was trying to avoid using the DOM to get the element, and since I'm using the [Polymer/pwa-starter-kit](https://github.com/Polymer/pwa-starter-kit), I'll stick to similar guidelines.

That being said, which way would be advised to implement the toggle method of [app-drawer](https://www.webcomponents.org/element/@polymer/app-layout/elements/app-drawer) (or any other method)?

**Comment by jsilvermist** [comment]
You can see how the drawer is toggled in the responsive drawer layout using Redux here: https://github.com/Polymer/pwa-starter-kit/tree/template-responsive-drawer-layout

**Comment by Anid4u2c** [comment]
@jsilvermist 
I believe that's what I'm accomplishing by manually setting the [app-drawer](https://github.com/Polymer/pwa-starter-kit/blob/template-responsive-drawer-layout/src/components/my-app.js#L181):
`<app-drawer .opened="${this._drawerOpened}" .persistent="${this._wideLayout}"
          @opened-changed="${this._drawerOpenedChanged}">` 

As soon as the [_drawerOpened](https://github.com/Polymer/pwa-starter-kit/blob/template-responsive-drawer-layout/src/components/my-app.js#L43) property is changed, it triggers the [stateChanged(state)](https://github.com/Polymer/pwa-starter-kit/blob/template-responsive-drawer-layout/src/components/my-app.js#L241) function.

According to the [PWA Starter Kit > Redux and state management](https://pwa-starter-kit.polymer-project.org/redux-and-state-management), and indicates that "stateChanged gets called any time the store updates", which means it is using Redux.

I'm sure there's more than one way to get it done, yet I'm hoping that this is similar to what contributors and members would do, so that further development doesn't require me to rewrite my code, you know?
