### ISSUE TITLE
npm run test failing in Windows 10

### ISSUE THREAD

**Issue by antz29** [Polymer/pwa-starter-kit#348]
I have cloned the typescript variant of the pwa-starter-kit, and currently `npm run test` fails. See the attached log for full details.

I'm on Windows 10.

It seems to be failing to connect to selenium (getting `org.openqa.selenium.SessionNotCreatedException`), as far as I can tell, selenium server is running fine.

See the full log here:
https://gist.github.com/antz29/9939087536a53c6429aa4da9963c339a

I have not made any modifications to the code at all, just trying to get it running.

Any ideas?

Many thanks!

John

**Comment by keanulee** [comment]
Have you tried https://www.softwaretestingmaterial.com/failed-to-launch-ie-driver-using-selenium/ (from Google results for "Enable Protected Mode Selenium IE")?

**Comment by antz29** [comment]
@keanulee So that was part of the issue, the other was the cobbled version of Chrome (due to organisational group policies here) that was being used. Thanks for the help!
