### ISSUE TITLE
no warning if java version is too high

### ISSUE THREAD

**Issue by etcraftdelivery** [Polymer/pwa-starter-kit#350]
better docs / warnings for java version need for running the selenium tests:

java 8 works. java 12 does not work.

**Comment by motss** [comment]
It only works well on java8.

**Comment by keanulee** [comment]
Correct, Java 8 is required. Related issues:

https://github.com/Polymer/tools/pull/586
https://github.com/Polymer/tools/issues/405

PR welcome for updating the README/docs.
