### ISSUE TITLE
npm install sinon-chai@2.14.0 requires a pair of sinon

### ISSUE THREAD

**Issue by jackeymason** [Polymer/pwa-starter-kit#351]
Trying to get started with PWA kit. 
I'm running Ubuntu 18.04 on an early 2015 Macbook pro
when running: npm install I'm getting:
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN sinon-chai@2.14.0 requires a peer of sinon@^1.4.0 || ^2.1.0 || ^3.0.0 || ^4.0.0 but none was installed.

I manually installed sinon via npm and tried running the npm again but getting the same issue.
The unit test and integration tests are failing, but don't want to address those till I'm sure my environment is sane.

**Comment by keanulee** [comment]
After `npm install`ing, what version of `web-component-tester` do you see in package-lock.json? On my macOS MacBook, I see:

```js
        "web-component-tester": {
          "version": "6.9.2",
          "resolved": "https://registry.npmjs.org/web-component-tester/-/web-component-tester-6.9.2.tgz",
          "integrity": "sha512-s2kB/+IE8XWcnxY1fqSpqTiiHEGHWgUWariAbiRlxmAvWSuvaCVNALHYebsZrLCNCLHKcJR8/sGv/bw0MWMvjw==",
          "dev": true,
          "requires": {
            ...
            "sinon": "^2.3.5",
            "sinon-chai": "^2.10.0",
            ...
          },
```

Note it depends on `sinon` and `sinon-chai`, so it shouldn't be missing that peer dependency.

About the `fsevents` warnings - `fsevents` is an optional downstream from `gulp > chokidar`, so it isn't needed on linux. It's probably trying to install from package-lock.json, so you can probably just `rm node_modules/ package-lock.json` and `npm i` again (similar issue: https://github.com/google/web-starter-kit/issues/796).
