### ISSUE TITLE
Question about dynamic imports as implemented in src/actions/app.js

### ISSUE THREAD

**Issue by schevtso** [Polymer/pwa-starter-kit#359]
I have a question about the function loadPage() in https://github.com/Polymer/pwa-starter-kit/blob/master/src/actions/app.js. 

On each of the lines 32, 38, 41, and 45, a module is imported dynamically via a call to import(), which returns a Promise. Those Promises might, hypothetically, take a long time to resolve. 

Why doesn't the code wait for the import() calls to resolve? In other words, shouldn't the proper calls be:
await import('...');
?

**Comment by hyperpress** [comment]
Good question I use await import('...') in my apps. Did something change that makes removing that an advantage. There's no explanation in the last PR.

**Comment by hyperpress** [comment]
Good question I use await import('...') in my apps. Did something change that makes removing that an advantage.
