### ISSUE TITLE
Links Route is slipping

### ISSUE THREAD

**Issue by Biggisb** [Polymer/pwa-starter-kit#360]
Hey there this is more like a question and no Bugg.
We cloned that pwa starter with Typescript and build our first demo app.
Now we implemented bootstrap and have a small problem. 
Every link i click with an empty anchor (<a href="#">... Jumpts to the Index page and does not stay on the same page. Is there a way to prevent that? We didnt find a solution for that.

**Comment by jsilvermist** [comment]
You mean like this?

```html
<a href="javascript:" @click=${doSomething}>Hi</a>
```

**Comment by Biggisb** [comment]
If i use bootstrap tabs for example where the id is used to detect the element to open. https://codepen.io/wizly/pen/BlKxo 
I have no "Control" over the "how to open" this apply for some other functions aswell.
