### ISSUE TITLE
Fulfill "fast time-to-interactive and first-paint through the PRPL pattern" promise

### ISSUE THREAD

**Issue by micheljung** [Polymer/pwa-starter-kit#374]
I Installed nodejs & npm, cloned this repo (its typescript branch), ran `npm install` followed by `npm start`, accessed http://127.0.0.1:8081 using Chrome 77, ran lighthouse audit (repeatedly) and here's the result:

![image](https://user-images.githubusercontent.com/1864183/62297024-a8a17080-b470-11e9-9b00-670066811d7e.png)

Not really what one's expecting by a minimalistic starter kit :-(

System

![image](https://user-images.githubusercontent.com/1864183/62297208-16e63300-b471-11e9-8c68-c5be24275f29.png)

Lighthouse settings

![image](https://user-images.githubusercontent.com/1864183/62297232-22d1f500-b471-11e9-9540-773c2e76bf33.png)

**Comment by abdonrd** [comment]
You need to build the project:

https://pwa-starter-kit.polymer-project.org/building-and-deploying

**Comment by motss** [comment]
Running an audit locally will affect the score unless you have your local server has all kinds of optimization built in when serving the assets like gzipping, etc.
