### ISSUE TITLE
Routing and browser back button

### ISSUE THREAD

**Issue by ivanovivelin** [Polymer/pwa-starter-kit#377]
Hi,

I currently have the following in my-app.js: 
```
${this._page === 'shoppingcart'?html`<reference-shopping-cart name="shoppingcart" class="page" ?active="${this._page.match(/^shoppingcart*/)}"></reference-shopping-cart>`:``}
${this._page === 'home'?html`<reference-home-page name="home" class="page active" ?active="${this._page === 'home'}"></reference-home-page>`:``}
```
If I navigate between shoppingcart and home page using the browser back and forward, the state of those components is never updated unless I do the conditional blocks above. Is there any other way to notify of the route change and re-trigger the component.

**Comment by sdyalor** [comment]
Ahm, event listeners?
