### ISSUE TITLE
app calls <component>.stateChanged(state) even when the component is inactive

### ISSUE THREAD

**Issue by lp74** [Polymer/pwa-starter-kit#379]
Hello,

the stateChanged(state) method of the PageViewElement classes (views) is invoked even if they are inactive and hidden.

How to address this issue?

**Comment by sdyalor** [comment]
Ahm, maybe using event listeners when something you want just happen once needed?

**Comment by smashah** [comment]
from the connect mixin ([here](https://github.com/Polymer/pwa-helpers/blob/master/src/connect-mixin.ts) ) you can see that the state is unsubscribed upon the ```disconnectedCallback``` lifecycle event.

From the [lit-element documentation](https://lit-element.polymer-project.org/guide/lifecycle) you can see that ```disconnectedCallback``` is called when:

> a component is removed from the document’s DOM

MyApp does not remove a PageViewElement component from the dom, It reacts to ```active``` being true/false and therefore it only 'hides' the component [as seen here](https://github.com/Polymer/pwa-starter-kit/blob/ec8f066786ca3fed326a36c087b5f474763b8079/src/components/my-app.js#L154)

```
       .page {
          display: none;
        }
        .page[active] {
          display: block;
        }
```

A possible solution to this would be to call ```this.disconnectedCallback``` in PageViewElement when ```active``` becomes false.

This may work:

```
shouldUpdate() {
if(!this.active) this.disconnectedCallback();
    return this.active;
  }
```

Try it and let us know if that works for you,

**Comment by lp74** [comment]
using immutability this is not an issue anymore.
