### ISSUE TITLE
Items in toolbar-list clickable through toolbar-top

### ISSUE THREAD

**Issue by mytiope** [Polymer/pwa-starter-kit#389]
Menu items in the toolbar-list can be clicked while they are behind the toolbar-top.

1. Scroll down the page to the bottom of the page.
2. Scroll up the page one scroll wheel click -- to reveal the toolbar-top, but not the toolbar-list.
3. Even though you cannot see the toolbar-list menu items, they are clickable.

It seems like the toolbar-list menu items should not be clickable in that case.  Can this be fixed with styling somehow?  I couldn't get z-indexes to help.  Maybe this is a generic app-header element bug (transform translate3d related?).

Chrome and Firefox both seem to act the same.

**Comment by sdyalor** [comment]
#373
