### ISSUE TITLE
PLEASE MARK AS IN MAINTENANCE

### ISSUE THREAD

**Issue by mercmobily** [Polymer/pwa-starter-kit#391]
The last commit to this project was six months ago. Issue #373 is clear about this.
The team behind it (Monica, Rob, Keanu, others) have either moved on to different companies, or different parts of Google.

And yet, in polymer-project.org, it's still not grey and it's marked as "prerelease":

![image](https://user-images.githubusercontent.com/2128734/75603732-4561e480-5b0c-11ea-9309-9828e07a5169.png)

It's time to mark it as "Maintenance" (although since it's been getting 0 commits for over 6 months, maybe "Obsolete" would be more appropriate) BOTH in Polymer's web site AND in the project's README.

In the website, I recommend linking to open-wc.org which is what developers are using instead -- if they are lucky enough to discover it. The only mention in the Polymer project is in this blog entry: https://github.com/Polymer/project/blob/master/Roadmap.md 

UPDATE: Please also take https://pwa-starter-kit.polymer-project.org/ offline -- or mark it clearly as obsolete/maintenance

**Comment by johnthad** [comment]
I largely agree, mostly because the starter kit does not seem to be going anywhere, and because [open-wc.org](https://open-wc.org/) is _very good_ and very well supported. OTOH, the starter kit apps are the most complete, well-documented examples I've found using `lit-element`. Additionally I'm getting a lot of mileage out of the `pwa-helpers`, especially `router.js` and `connect-mixin.js`. Marking the entire project "Obsolete" would make it less like that others could benefit from what the starter kit offers.

**Comment by hyperpress** [comment]
I'd argue that not having a more fully functional PWA starter in lit-element cuts the project off from a lot of potential users/developers. The PWA examples provided a different levels of complexity, with the books example the most. If open-wc could provide a starter that provides a fuller PWA examples built with web components, that would be the best example. Polymer team members have largely been reduced to just a few people as far as I can tell and open-wc would be a more stable, maintained version I think. I just released a PWA Starter that was based on PWA starter kit. It was the easiest way for me to more quickly up to speed with using Polymer projects, including lit-element. But I totally agree that having an un-maintained version, again, sends the wrong message.

**Comment by mercmobily** [comment]
What really worries me is that this project seems so abandoned, there aren't even enough resources to pick up the pieces and mark obsolete things as obsolete.
This wouldn't bother me if this makes amazing things like lit-html look bad too.

@justinfagnani Any strings you can pull?

**Comment by MehdiRaash** [comment]
when I see a **notification** from this Polymer, I got happy! hm... That was a mist.

**Comment by arthurevans** [comment]
Thanks @mercmobily ... Yeah, it didn't really fit either "Maintenance" or "Obsolete," so it kind of languished for lack of a good name. Thanks for the nudge! Updated here, we'll push out updates to the other locations.

**Comment by mercmobily** [comment]
If you give me the right permissions, I will be happy to close the pending issues with the notice:

------------------------------------------------------
Status: No longer under development
This project is no longer under development.

If you're interested in continuing to use PWA Starter Kit, feel free to fork and modify it as you like.

If you want to start a new application project using LitElement, the open-wc application scaffold generator is one good starting point.
-----------------------------------------------------------

I would also change the issue template so that it states clearly that the project is no longer being developed. Or, even better, disable issues altogether.

I am happy to do the work -- let me know.
