### ISSUE TITLE
package dependencies excess (and resulting exposure)

### ISSUE THREAD

**Issue by jimmont** [Polymer/pwa-starter-kit#83]
since this seems to be a funnel for so many things, and I'm a slight participant in this stuff (for what it's worth), I feel compelled to point out:
- there are notable issues of varying severity for a number of included dependencies (51 at time of this issue--use `npm audit` after install/update for current infos)
- the number of packages (2554) and contributors (1964) seems a little excessive

post-install at time of reporting, not including audit:
```(node:11013) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
added 2554 packages from 1964 contributors in 168.548s
[!] 51 vulnerabilities found [16961 packages audited]
    Severity: 31 low | 11 moderate | 7 high | 2 critical
    Run `npm audit` for more detail```

**Comment by notwaldorf** [comment]
those are all the `devDependencies` we use for testing and deploying (the polymer CLI, etc). If you just install the production dependencies, it's significantly smaller.

**Comment by jimmont** [comment]
thanks @notwaldorf how should I do this (or read in with the relevant detail) and what should I be reading to understand how to bundle this for a release?

**Comment by notwaldorf** [comment]
Oh, if the concern is for bundling, this is very minor. There's a [deploying](https://github.com/Polymer/pwa-starter-kit/wiki/5.-Building-&-Deploying) wiki page that covers deployment, but the tldr is that `npm run build` will create all your minimal bundles for you, which are just based on the `src` (and that bundle won't depend on things like `wct`, `puppeteer`, `mocha`, and the actual polymer cli, which make up 90% of those dependencies)

**Comment by jimmont** [comment]
Yes that's my ultimate goal, I'm converting a polymer 2 app to 3 in nwjs (like electron) and trying to get a handle on the range of details involved, especially the size of the assets and how to generate them. Thanks very much. My environment has no NODE_ENV set so wasn't expecting all the dependencies to install. Looks like this must be the default behavior and I've never noticed. If you know how to do otherwise I'd like to know as a curiosity--otherwise this solves my issue. Thx
