### ISSUE TITLE
PolymerCLI runs bower for PWA-starter kit

### ISSUE THREAD

**Issue by raydaly** [Polymer/pwa-starter-kit#84]
Ran polymercli (v 1.7) init and selected PWA-starter-kit. The process then tried to run bower and stopped on the error that there was no "bower.json". Obviously with Polymer 3.0 bower should not be invoked.

**Comment by notwaldorf** [comment]
We support `init`via the CLI yet. As per the [setup instructions](https://github.com/Polymer/pwa-starter-kit/wiki/2.-Setup) you should run `git clone` instead
