### ISSUE TITLE
[feature request] Add a push notifications sample

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/pwa-starter-kit#86]
(request received at the I/O sandbox from @ozasadnyy)

This should probably live in one of the apps (maybe `flash-cards`, to remind you to practice?), but we could also add an explanation on the wiki

**Comment by keanulee** [comment]
Not sure which demo it should go in (it'll require server support), but I wrote some code to do push notifications before which may be helpful - https://github.com/googlearchive/summit-2017/blob/master/elements/push-notifications.html

**Comment by notwaldorf** [comment]
Do you think we can we do some Firebase functions or a simple Glitch server maybe for the server bits?

**Comment by davie-robertson** [comment]
It would be great to see some Firebase integration in these sample apps.

**Comment by Protoss78** [comment]
I'm currently playing around with it. Will share my repo once I have something up and running. But I will use redux-saga instead of thunk in my example. So it will look a little bit different from a structural perspective.

**Comment by Protoss78** [comment]
Ok. I got my initial sample up and running. For simplicity reasons I removed the shop related components, added firebase authentication and switched from redux-thunk to redux-saga. Mainly because of personal preferences. Here is the link to my repo: https://github.com/Protoss78/pwa-firebase-saga-kit

**Comment by dipernaa** [comment]
any updates on this?
