### ISSUE TITLE
_firstRenreded called before _render with lazy loaded elements

### ISSUE THREAD

**Issue by jrabary** [Polymer/pwa-starter-kit#93]
Getting and initializing a child element of the shadow Dom during the `_firstRendered` callback is not working in the following case:

```
class MyView2 extends connect(store)(PageViewElement) {
  _render(props) {
    return html`
      <canvas id="draw"></canvas>
    `;
  }

  static get properties() { return {
    // This is the data from the store.
    _clicks: Number,
    _value: Number
  }}

  _firstRendered() {
    console.log(this.shadowRoot.getElementById('draw')); // log null
  }

   _didRender(props, changedProps, prevProps) {
       console.log(this.shadowRoot.getElementById('draw')); // log canvas
   }

  // This is called every time something is updated in the store.
  _stateChanged(state) {
    this._clicks = state.counter.clicks;
    this._value = state.counter.value;
  }
}
```
It seems that the `_firstRendered` is called before `_render` in this situation. The original discussion is here https://github.com/Polymer/lit-element/issues/57

**Comment by elarb** [comment]
Can confirm, confronted something similar earlier today when trying to access a DOM node at `_firstRendered()` (Chrome 66)

**Comment by elarb** [comment]
Changing `_loadPage()` in `my-app.js` from an `async` function to a normal function seems to resolve the issue.

**Comment by jrabary** [comment]
using normal function is working for me as well.
